fix back

diff --git a/.github/workflows/_accessibility-validation.yml b/.github/workflows/_accessibility-validation.yml
--- a/.github/workflows/_accessibility-validation.yml
+++ b/.github/workflows/_accessibility-validation.yml
@@ -5,13 +5,12 @@ on: workflow_call
 jobs:
   build:
     runs-on: ubuntu-latest
-
     steps:
-      - uses: actions/checkout@v2
-      - uses: actions/setup-node@v2
+      - uses: actions/checkout@v3
+      - uses: actions/setup-node@v3
         with:
-          node-version: "16"
-          cache: "npm"
+          node-version: 16
+          cache: npm
 
       - uses: actions/cache@v3
         id: cache
@@ -23,16 +22,21 @@ jobs:
         if: steps.cache.outputs.cache-hit != 'true'
         run: npm ci
       - name: Build Site
-        run: npm run nx build docs
+        run: npx nx run docs:build
 
       - name: Scan for accessibility issues
-        uses: microsoft/accessibility-insights-action@v2
+        uses: microsoft/accessibility-insights-action@v3
         with:
           repo-token: ${{ secrets.GITHUB_TOKEN }}
           site-dir: ${{ github.workspace }}/dist/apps/docs
+          # (will aply to version 3)
+          # due to action fail to pierce in shadowed links,
+          # all links must be explicitly specified, seperated by space
+          input-urls: http://localhost:12345 http://localhost:12345/components/accordion http://localhost:12345/components/accordion-item http://localhost:12345/components/badge http://localhost:12345/components/banner http://localhost:12345/components/breadcrumb http://localhost:12345/components/breadcrumb-item http://localhost:12345/components/button http://localhost:12345/components/calendar http://localhost:12345/components/calendar-event http://localhost:12345/components/icon http://localhost:12345/components/layout http://localhost:12345/components/popup http://localhost:12345/components/side-drawer http://localhost:12345/components/sidenav-item http://localhost:12345/components/sidenav-disclosure http://localhost:12345/components/text http://localhost:12345/components/tooltip http://localhost:12345/components/progress http://localhost:12345/components/progress-ring http://localhost:12345/components/card http://localhost:12345/components/text-field http://localhost:12345/components/fab http://localhost:12345/components/action-group http://localhost:12345/components/note http://localhost:12345/components/checkbox http://localhost:12345/components/dialog http://localhost:12345/components/header http://localhost:12345/components/sidenav http://localhost:12345/components/divider
 
       - name: Upload report artifact
-        uses: actions/upload-artifact@v2
+        if: success() || failure()
+        uses: actions/upload-artifact@v3
         with:
           name: accessibility-reports
           path: ${{ github.workspace }}/_accessibility-reports
