now?

diff --git a/.github/workflows/_accessibility-validation.yml b/.github/workflows/_accessibility-validation.yml
--- a/.github/workflows/_accessibility-validation.yml
+++ b/.github/workflows/_accessibility-validation.yml
@@ -10,24 +10,23 @@ jobs:
       - uses: actions/checkout@v3
       - uses: actions/setup-node@v3
         with:
-          node-version: '16'
-          cache: 'npm'
+          node-version: 16
 
-      - name: Install Dependencies
-        run: npm ci
+      # Insert any jobs here required to build your website files
 
-      - name: Build Site
-        run: npm run nx build docs
-
-      - name: Scan for accessibility issues (with static-site-dir)
+      - name: Scan for accessibility issues
         uses: microsoft/accessibility-insights-action@v3
         with:
-            static-site-dir: ${{ github.workspace }}/dist/apps/docs
-            static-site-port: 12345
-            input-urls: http://localhost:12345/components/sidenav
+          # Provide either static-site-dir or url
+          # static-site-dir: ${{ github.workspace }}/path-to-built-website
+          # url: your-website-url
+
+          # Provide any additional inputs here
+          # fail-on-accessibility-error: false
 
       - name: Upload report artifact
-        uses: actions/upload-artifact@v2
+        if: success() || failure()
+        uses: actions/upload-artifact@v3
         with:
           name: accessibility-reports
           path: ${{ github.workspace }}/_accessibility-reports
