fix(release-please): add job to create required vivid-vue tag (VIV-000)

diff --git a/.github/workflows/release-please.yml b/.github/workflows/release-please.yml
--- a/.github/workflows/release-please.yml
+++ b/.github/workflows/release-please.yml
@@ -5,8 +5,47 @@ on:
 
 name: release-please
 jobs:
+  tag-vivid-vue:
+    # As we've instructed release-please not to create a vivid-vue release for now, we need to create the tag ourselves
+    # This job will check if a tag for the current version of vivid-vue exists, and if not, create it
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v3
+        with:
+          fetch-depth: 0
+      - name: Check tag
+        id: check_tag
+        run: |
+          TAG_NAME=vivid-vue-v$(node -p "require('./libs/vue-wrappers/package.json').version")
+          echo "Vivid-vue tag name: ${TAG_NAME}"
+
+          git show-ref --tags --verify --quiet "refs/tags/${TAG_NAME}"
+          exit_code=$?
+          if [[ $exit_code -eq 0 ]]; then
+            echo "Tag ${TAG_NAME} exists"
+          else
+            echo "Tag ${TAG_NAME} does not exist"
+            echo "::set-output name=missing_tag_name::${TAG_NAME}"
+          fi
+      - name: Create Tag
+        if: steps.check_tag.outputs.missing_tag_name
+        uses: actions/github-script@v6
+        env:
+          TAG_NAME: ${{ steps.check_tag.outputs.missing_tag_name }}
+        with:
+          script: |
+            const { TAG_NAME } = process.env
+            github.rest.git.createRef({
+                owner: context.repo.owner,
+                repo: context.repo.repo,
+                ref: `refs/tags/${TAG_NAME}`,
+                sha: context.sha
+            })
+
   release-please:
     runs-on: ubuntu-latest
+    needs: tag-vivid-vue
     outputs:
       releases_created: ${{ steps.release.outputs.releases_created }}
     steps:
